(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Morning Calsmi, Welcome to Coot. (revision 5348)
[with guile 1.8.8 embedded]
[with python 2.7.9 embedded]")
(set-filter-fileselection-filenames 1)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 15.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 0)
(set-idle-function-rotate-angle  1.50)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good morning Callum. Welcome to Coot")
(set-display-lists-for-maps 0)
(set-filter-fileselection-filenames 1)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 15.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 0)
(set-idle-function-rotate-angle  1.50)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(handle-read-draw-molecule-with-recentre "shaftTrunc.pdb" 1)
(use-graphics-interface-state)
(coot-checked-exit 0)
(clear-backups-maybe)
(stereo-mode-state)
(save-state)
