filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Morning Calsmi, Welcome to Coot. (revision 5348)
[with guile 1.8.8 embedded]
[with python 2.7.9 embedded]")
set_filter_fileselection_filenames (1)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (15.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (0)
set_idle_function_rotate_angle ( 1.50)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good morning Callum. Welcome to Coot")
set_display_lists_for_maps (0)
set_filter_fileselection_filenames (1)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (15.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (0)
set_idle_function_rotate_angle ( 1.50)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
handle_read_draw_molecule_with_recentre ("shaftTrunc.pdb", 1)
use_graphics_interface_state ()
coot_checked_exit (0)
;; # DIRECT SCHEME ((clear-backups-maybe))
stereo_mode_state ()
save_state ()
