filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Morning Stocklab, Welcome to Coot. 0.7.1 (revision 4660)  [with guile 1.8.8 embedded] [with python 2.7.6 embedded]")
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (10.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle ( 1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good morning Stock. Welcome to Coot")
set_display_lists_for_maps (0)
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (10.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle ( 1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/0_PO4b.pdb", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/1_PO4b.pdb", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/2_PO4b.pdb", 1)
set_clipping_front (-0.20)
set_clipping_back (-0.20)
set_clipping_front (-0.70)
set_clipping_back (-0.70)
set_clipping_front (-1.70)
set_clipping_back (-1.70)
set_clipping_front (-3.70)
set_clipping_back (-3.70)
set_clipping_front (-5.70)
set_clipping_back (-5.70)
set_clipping_front (-9.00)
set_clipping_back (-9.00)
set_clipping_front (-10.00)
set_clipping_back (-10.00)
graphics_molecule_bond_type (0)
graphics_molecule_bond_type (1)
graphics_molecule_bond_type (2)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/PO4.pdb", 1)
graphics_molecule_bond_type (3)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/PO4_O.pdb", 1)
graphics_molecule_bond_type (4)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/2_ADPe.pdb", 1)
graphics_molecule_bond_type (5)
close_molecule (5)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/0_PO4e.pdb", 1)
graphics_molecule_bond_type (6)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/1_PO4e.pdb", 1)
graphics_molecule_bond_type (7)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/2_PO4e.pdb", 1)
graphics_molecule_bond_type (8)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/0_ADPb.pdb", 0)
graphics_molecule_bond_type (9)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/2_PO4h.pdb", 0)
graphics_molecule_bond_type (10)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/1_PO4h.pdb", 0)
graphics_molecule_bond_type (11)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/2_ADPb.pdb", 0)
graphics_molecule_bond_type (12)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/0_PO4h.pdb", 0)
graphics_molecule_bond_type (13)
coot_checked_exit (0)
;; # DIRECT SCHEME ((clear-backups-maybe))
stereo_mode_state ()
stereo_mode_state ()
save_state ()
