; These commands are the saved state of coot.  You can evaluate them
; using "Calculate->Run Script...".
;;molecule-info: 0_PO4b.pdb
;;molecule-info: 1_PO4b.pdb
;;molecule-info: 2_PO4b.pdb
;;molecule-info: PO4.pdb
;;molecule-info: PO4_O.pdb
;;molecule-info: 0_PO4e.pdb
;;molecule-info: 1_PO4e.pdb
;;molecule-info: 2_PO4e.pdb
;;molecule-info: 0_ADPb.pdb
;;molecule-info: 2_PO4h.pdb
;;molecule-info: 1_PO4h.pdb
;;molecule-info: 2_ADPb.pdb
;;molecule-info: 0_PO4h.pdb
(set-graphics-window-size 1309 1017)
(set-graphics-window-position 20 20)
(set-display-control-dialog-position 1491 37)
(vt-surface 2)
(set-clipping-front -10.00)
(set-clipping-back -10.00)
(set-map-radius 10.00)
(set-iso-level-increment  0.0500)
(set-diff-map-iso-level-increment  0.0050)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-flag 1)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-swap-difference-map-colours 0)
(set-background-colour  0.00  0.00  0.00)
(set-symmetry-size 13.00)
(set-symmetry-colour-merge  0.50)
(set-symmetry-colour  0.10  0.20  0.80)
(set-symmetry-atom-labels-expanded 0)
(set-active-map-drag-flag 1)
(set-show-aniso 0)
(set-aniso-probability 50.00)
(set-smooth-scroll-steps 40)
(set-smooth-scroll-limit 10.00)
(set-font-size 2)
(set-rotation-centre-size  0.10)
(set-do-anti-aliasing 0)
(set-default-bond-thickness 5)
(handle-read-draw-molecule "0_PO4b.pdb")
(set-molecule-bonds-colour-map-rotation 0 21.00)
(set-mol-displayed 0 0)
(set-mol-active 0 0)
(set-draw-hydrogens 0 1)
(handle-read-draw-molecule "1_PO4b.pdb")
(set-molecule-bonds-colour-map-rotation 1 42.00)
(set-draw-hydrogens 1 1)
(handle-read-draw-molecule "2_PO4b.pdb")
(set-molecule-bonds-colour-map-rotation 2 63.00)
(set-mol-displayed 2 0)
(set-mol-active 2 0)
(set-draw-hydrogens 2 1)
(handle-read-draw-molecule "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/PO4.pdb")
(set-molecule-bonds-colour-map-rotation 3 84.00)
(set-mol-displayed 3 0)
(set-mol-active 3 0)
(set-draw-hydrogens 3 1)
(handle-read-draw-molecule "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/PO4_O.pdb")
(set-molecule-bonds-colour-map-rotation 4 105.00)
(set-mol-displayed 4 0)
(set-mol-active 4 0)
(set-draw-hydrogens 4 1)
(handle-read-draw-molecule "0_PO4e.pdb")
(set-molecule-bonds-colour-map-rotation 5 147.00)
(set-draw-hydrogens 5 1)
(handle-read-draw-molecule "1_PO4e.pdb")
(set-molecule-bonds-colour-map-rotation 6 168.00)
(set-mol-displayed 6 0)
(set-mol-active 6 0)
(set-draw-hydrogens 6 1)
(handle-read-draw-molecule "2_PO4e.pdb")
(set-molecule-bonds-colour-map-rotation 7 189.00)
(set-mol-displayed 7 0)
(set-mol-active 7 0)
(set-draw-hydrogens 7 1)
(handle-read-draw-molecule "0_ADPb.pdb")
(set-molecule-bonds-colour-map-rotation 8 210.00)
(set-mol-displayed 8 0)
(set-mol-active 8 0)
(set-draw-hydrogens 8 1)
(handle-read-draw-molecule "2_PO4h.pdb")
(set-molecule-bonds-colour-map-rotation 9 231.00)
(set-mol-displayed 9 0)
(set-mol-active 9 0)
(set-draw-hydrogens 9 1)
(handle-read-draw-molecule "1_PO4h.pdb")
(set-molecule-bonds-colour-map-rotation 10 252.00)
(set-mol-displayed 10 0)
(set-mol-active 10 0)
(set-draw-hydrogens 10 1)
(handle-read-draw-molecule "2_ADPb.pdb")
(set-molecule-bonds-colour-map-rotation 11 273.00)
(set-mol-displayed 11 0)
(set-mol-active 11 0)
(set-draw-hydrogens 11 1)
(handle-read-draw-molecule "0_PO4h.pdb")
(set-molecule-bonds-colour-map-rotation 12 294.00)
(set-draw-hydrogens 12 1)
(set-matrix 60.00)
(set-show-symmetry-master 0)
(set-go-to-atom-molecule 12)
(scale-zoom  0.51)
(set-rotation-centre 30.82  5.32 147.91)
(set-view-quaternion -0.0927 -0.3578 -0.9256 -0.0821)
(post-display-control-window)
