(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Morning Stocklab, Welcome to Coot. 0.7.1 (revision 4660)  [with guile 1.8.8 embedded] [with python 2.7.6 embedded]")
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 10.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle  1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good morning Stock. Welcome to Coot")
(set-display-lists-for-maps 0)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 10.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle  1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/0_PO4b.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/1_PO4b.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/2_PO4b.pdb" 1)
(set-clipping-front -0.20)
(set-clipping-back -0.20)
(set-clipping-front -0.70)
(set-clipping-back -0.70)
(set-clipping-front -1.70)
(set-clipping-back -1.70)
(set-clipping-front -3.70)
(set-clipping-back -3.70)
(set-clipping-front -5.70)
(set-clipping-back -5.70)
(set-clipping-front -9.00)
(set-clipping-back -9.00)
(set-clipping-front -10.00)
(set-clipping-back -10.00)
(graphics-molecule-bond-type 0)
(graphics-molecule-bond-type 1)
(graphics-molecule-bond-type 2)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/PO4.pdb" 1)
(graphics-molecule-bond-type 3)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/PO4_O.pdb" 1)
(graphics-molecule-bond-type 4)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/2_ADPe.pdb" 1)
(graphics-molecule-bond-type 5)
(close-molecule 5)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/0_PO4e.pdb" 1)
(graphics-molecule-bond-type 6)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/1_PO4e.pdb" 1)
(graphics-molecule-bond-type 7)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/2_PO4e.pdb" 1)
(graphics-molecule-bond-type 8)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/0_ADPb.pdb" 0)
(graphics-molecule-bond-type 9)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/2_PO4h.pdb" 0)
(graphics-molecule-bond-type 10)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/1_PO4h.pdb" 0)
(graphics-molecule-bond-type 11)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/2_ADPb.pdb" 0)
(graphics-molecule-bond-type 12)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/FType/0_PO4h.pdb" 0)
(graphics-molecule-bond-type 13)
(coot-checked-exit 0)
(clear-backups-maybe)
(stereo-mode-state)
(stereo-mode-state)
(save-state)
