# These commands are the saved state of coot.  You can evaluate them
# using "Calculate->Run Script...".
#;;molecule-info: 0_PO4b.pdb
#;;molecule-info: 1_PO4b.pdb
#;;molecule-info: 2_PO4b.pdb
#;;molecule-info: PO4.pdb
#;;molecule-info: PO4_O.pdb
#;;molecule-info: 0_PO4e.pdb
#;;molecule-info: 1_PO4e.pdb
#;;molecule-info: 2_PO4e.pdb
#;;molecule-info: 0_ADPb.pdb
#;;molecule-info: 2_PO4h.pdb
#;;molecule-info: 1_PO4h.pdb
#;;molecule-info: 2_ADPb.pdb
#;;molecule-info: 0_PO4h.pdb
set_graphics_window_size (1309, 1017)
set_graphics_window_position (20, 20)
set_display_control_dialog_position (1491, 37)
vt_surface (2)
set_clipping_front (-10.00)
set_clipping_back (-10.00)
set_map_radius (10.00)
set_iso_level_increment ( 0.0500)
set_diff_map_iso_level_increment ( 0.0050)
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_flag (1)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_swap_difference_map_colours (0)
set_background_colour ( 0.00,  0.00,  0.00)
set_symmetry_size (13.00)
set_symmetry_colour_merge ( 0.50)
set_symmetry_colour ( 0.10,  0.20,  0.80)
set_symmetry_atom_labels_expanded (0)
set_active_map_drag_flag (1)
set_show_aniso (0)
set_aniso_probability (50.00)
set_smooth_scroll_steps (40)
set_smooth_scroll_limit (10.00)
set_font_size (2)
set_rotation_centre_size ( 0.10)
set_do_anti_aliasing (0)
set_default_bond_thickness (5)
handle_read_draw_molecule ("0_PO4b.pdb")
set_molecule_bonds_colour_map_rotation (0, 21.00)
set_mol_displayed (0, 0)
set_mol_active (0, 0)
set_draw_hydrogens (0, 1)
handle_read_draw_molecule ("1_PO4b.pdb")
set_molecule_bonds_colour_map_rotation (1, 42.00)
set_draw_hydrogens (1, 1)
handle_read_draw_molecule ("2_PO4b.pdb")
set_molecule_bonds_colour_map_rotation (2, 63.00)
set_mol_displayed (2, 0)
set_mol_active (2, 0)
set_draw_hydrogens (2, 1)
handle_read_draw_molecule ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/PO4.pdb")
set_molecule_bonds_colour_map_rotation (3, 84.00)
set_mol_displayed (3, 0)
set_mol_active (3, 0)
set_draw_hydrogens (3, 1)
handle_read_draw_molecule ("/Users/stocklab/Documents/Callum/rt1NG/rt1/structureData/PO4_O.pdb")
set_molecule_bonds_colour_map_rotation (4, 105.00)
set_mol_displayed (4, 0)
set_mol_active (4, 0)
set_draw_hydrogens (4, 1)
handle_read_draw_molecule ("0_PO4e.pdb")
set_molecule_bonds_colour_map_rotation (5, 147.00)
set_draw_hydrogens (5, 1)
handle_read_draw_molecule ("1_PO4e.pdb")
set_molecule_bonds_colour_map_rotation (6, 168.00)
set_mol_displayed (6, 0)
set_mol_active (6, 0)
set_draw_hydrogens (6, 1)
handle_read_draw_molecule ("2_PO4e.pdb")
set_molecule_bonds_colour_map_rotation (7, 189.00)
set_mol_displayed (7, 0)
set_mol_active (7, 0)
set_draw_hydrogens (7, 1)
handle_read_draw_molecule ("0_ADPb.pdb")
set_molecule_bonds_colour_map_rotation (8, 210.00)
set_mol_displayed (8, 0)
set_mol_active (8, 0)
set_draw_hydrogens (8, 1)
handle_read_draw_molecule ("2_PO4h.pdb")
set_molecule_bonds_colour_map_rotation (9, 231.00)
set_mol_displayed (9, 0)
set_mol_active (9, 0)
set_draw_hydrogens (9, 1)
handle_read_draw_molecule ("1_PO4h.pdb")
set_molecule_bonds_colour_map_rotation (10, 252.00)
set_mol_displayed (10, 0)
set_mol_active (10, 0)
set_draw_hydrogens (10, 1)
handle_read_draw_molecule ("2_ADPb.pdb")
set_molecule_bonds_colour_map_rotation (11, 273.00)
set_mol_displayed (11, 0)
set_mol_active (11, 0)
set_draw_hydrogens (11, 1)
handle_read_draw_molecule ("0_PO4h.pdb")
set_molecule_bonds_colour_map_rotation (12, 294.00)
set_draw_hydrogens (12, 1)
set_matrix (60.00)
set_show_symmetry_master (0)
set_go_to_atom_molecule (12)
scale_zoom ( 0.51)
set_rotation_centre (30.82,  5.32, 147.91)
set_view_quaternion (-0.0927, -0.3578, -0.9256, -0.0821)
post_display_control_window ()
